version: '3.3'
services:
    pkgserver:
        image: juliapackaging/pkgserver.jl
        user: $UID
        restart: unless-stopped
        ports:
            - 8000:8000
        volumes:
            - ./cache:/app/cache
        environment:
            PKGSERVER_HOST: "0.0.0.0"
            PKGSERVER_PORT: "8000"
            PKGSERVER_STORAGESERVERS: "https://us-east.storage.julialang.org"
        labels:
            # Tell watchtower to auto-update this guy
            com.centurylinklabs.watchtower.enable: true

    # Auto-reload docker containers when their images are updated
    watchtower:
        image: containrrr/watchtower
        restart: unless-stopped
        volumes:
            # Mount the docker socket
            - /var/run/docker.sock:/var/run/docker.sock
        command: --cleanup --label-enable
