version: '3.3'
services:
    pkgserver:
        image: juliapackaging/pkgserver.jl
        user: $UID
        restart: unless-stopped
        ports:
            - 8000:8000
        volumes:
            - ./storage:/app/storage
            - ./logs/pkgserver:/app/logs
        environment:
            JULIA_PKG_SERVER: "0.0.0.0:8000"
            JULIA_PKG_SERVER_STORAGE_SERVERS: "https://us-east.storage.julialang.org,https://kr.storage.julialang.org"
            JULIA_PKG_SERVER_STORAGE_ROOT: "/app/storage"
            JULIA_PKG_SERVER_LOGS_DIR: "/app/logs"
        labels:
            # Tell watchtower to auto-update this guy
            com.centurylinklabs.watchtower.enable: true

    # Auto-reload docker containers when their images are updated
    watchtower:
        image: containrrr/watchtower
        restart: unless-stopped
        volumes:
            # Mount the docker socket
            - /var/run/docker.sock:/var/run/docker.sock
        command: --cleanup --label-enable
